/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
	`kotlin-dsl` apply false
	`embedded-kotlin` apply false

	id("dev.opensavvy.conventions.plugin")
}

allprojects {
	pluginManager.apply("dev.opensavvy.conventions.plugin")
}
